name: rally
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Eczar
      fonts:
        - asset: fonts/Eczar/Eczar-Regular.ttf
          weight: 400
        - asset: fonts/Eczar/Eczar-bold.ttf
          weight: 700
    - family: RobotoCondensed
      fonts:
        - asset: fonts/RobotoCondensed/RobotoCondensed-Light.ttf
          weight: 300
        - asset: fonts/RobotoCondensed/RobotoCondensed-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/RobotoCondensed/RobotoCondensed-Regular.ttf
          weight: 400
        - asset: fonts/RobotoCondensed/RobotoCondensed-Italic.ttf
          weight: 400
          style: italic
        - asset: fonts/RobotoCondensed/RobotoCondensed-Bold.ttf
          weight: 700
        - asset: fonts/RobotoCondensed/RobotoCondensed-BoldItalic.ttf
          weight: 700
          style: italic
